spring:
  servlet:
    multipart:
      max-file-size: 5MB
  jpa:
    open-in-view: true
  config:
    import: classpath:application-db.yml, classpath:application-security.yml

server:
  servlet:
    session:
      persistent: false